name: Create branch from issue

permissions:
  contents: write

inputs:
  base-branch:
    description: 'Base branch'
    required: true
  branch-prefix:
    description: 'Branch prefix (e.g., issue, feat, fix)'
    required: true
    default: 'issue'
  ignored-issues:
    description: 'Comma-separated ignored issue types (e.g., bug,docs)'
    required: false
    default: 'bug,docs'

outputs:
  branch-name:
    description: 'Created branch name'
    value: ${{ steps.create-branch.outputs.branch-name }}

runs:
  using: composite
  steps:
    - name: Create branch from base branch
      id: create-branch
      uses: actions/github-script@v7
      with:
        script: |
          const issueNumber = context.payload.issue.number;
          const issueTitle = context.payload.issue.title;

          // 스킵 조건 확인
          const ignoredList = '${{ inputs.ignored-issues }}'
            .split(',')
            .map(x => x.trim().toLowerCase());
          const isIgnored = ignoredList.some(keyword => issueTitle.toLowerCase().includes(keyword));
          if (isIgnored) {
            console.log(`⛔ Issue title contains ignored keyword. Skipping branch creation.`);
            core.setOutput('branch-name', '');
            return;
          }

          const issueAuthor = context.payload.issue.user.login;
          const baseBranch = '${{ inputs.base-branch }}';
          const prefix = '${{ inputs.branch-prefix }}';
          const targetBranch = `${prefix}/${issueNumber}`;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // 기본 브랜치에서 커밋 SHA 가져오기
          console.log(`🔍 Getting commit SHA for ${baseBranch} branch`);
          const base = await github.rest.repos.getBranch({
            owner,
            repo,
            branch: baseBranch,
          });
          const baseSha = base.data.commit.sha;

          // 브랜치 생성
          console.log(`📝 Creating branch ${targetBranch}`);
          try {
            await github.rest.git.createRef({
              owner,
              repo,
              ref: `refs/heads/${targetBranch}`,
              sha: baseSha,
            });
          } catch (err) {
            if (err.status === 422) {
              console.log('⚠️ Branch already exists. Skipping.');
            } else {
              throw err;
            }
          }

          // 기본 브랜치의 트리 SHA 가져오기
          console.log(`🔍 Getting tree SHA for ${baseBranch} branch`);
          const baseCommit = await github.rest.git.getCommit({
            owner,
            repo,
            commit_sha: baseSha,
          });
          const treeSha = baseCommit.data.tree.sha;

          // 빈 커밋 생성
          console.log(`📝 Creating empty commit for ${targetBranch}`);
          const emptyCommit = await github.rest.git.createCommit({
            owner,
            repo,
            message: `Created branch for issue #${issueNumber}\n\n[skip ci]`,
            tree: treeSha,
            parents: [baseSha],
          });

          // 브랜치 업데이트
          console.log(`🔄 Updating branch ${targetBranch}`);
          await github.rest.git.updateRef({
            owner,
            repo,
            ref: `heads/${targetBranch}`,
            sha: emptyCommit.data.sha,
            force: false,
          });

          console.log(`✅ Created branch ${targetBranch}`);
          
          // 생성된 브랜치명 출력
          core.setOutput('branch-name', targetBranch);
