name: Create pull request

inputs:
  branch-name:
    description: 'Target branch name (e.g., issue/123, feat/login)'
    required: true

runs:
  using: composite
  steps:
    - name: Create pull request
      uses: actions/github-script@v7
      with:
        script: |
          const issueNumber = context.payload.issue.number;
          const issueTitle = context.payload.issue.title;
          const issueAuthor = context.payload.issue.user.login;
          const targetBranch = '${{ inputs.branch-name }}';
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // PR 생성
          console.log(`📝 Creating PR for issue #${issueNumber} from branch ${targetBranch}`);
          const pr = await github.rest.pulls.create({
            owner,
            repo,
            title: `${issueTitle}`,
            head: targetBranch,
            base: 'develop',
            body: `Closes #${issueNumber}`,
            draft: true
          });

          // PR에 assignee 할당
          console.log(`👤 Assigning @${issueAuthor} to PR #${pr.data.number}`);
          await github.rest.issues.addAssignees({
            owner,
            repo,
            issue_number: pr.data.number,
            assignees: [issueAuthor]
          });

          console.log(`✅ Created PR #${pr.data.number} and assigned @${issueAuthor}`);
