name: '🐛 버그 추적'
description: '기존 설계 목적과 다르게 동작하는 기능 추적'
title: '[BUG] '
labels:
  - 'Bug :bug:'
assignees: []

body:
  - type: textarea
    id: bug-description
    attributes:
      label: 📌 어떤 버그인가요? (필수)
      description: |
        버그의 증상을 3줄 이내로 간결하게 설명해주세요.
        버그 발생 조건을 알려주세요. 정상 동작은 무엇이고, 현재 어떻게 동작하나요?
      placeholder: |
        예시:
        - 현재 비밀번호 정책은 영문, 숫자, 특수문자를 혼합하도록 되어 있음
        - 그러나 검증이 정상적으로 이루어지지 않아 잘못된 비밀번호로 회원가입이 가능한 상황
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 💻 발생 환경
      description: 버그가 발생하는 환경을 작성해주세요. (필수)
      placeholder: |
        - iPhone 15 / Galaxy Note 20
        - iOS 17.1 / Android 15
        - Chrome 124 / Safari
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: 🔁 재현 단계 (필수)
      description: 버그가 발생한 과정을 단계별로 작성해주세요.
      placeholder: |
        예시:
        1. 회원가입 페이지 접속
        2. 비밀번호에 'abc' 입력
        3. 제출 버튼 클릭
        4. 예상과 다르게 성공 메시지가 출력됨(abc - 비밀번호 조건에 맞지 않음)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 심각도 (필수)
      description: 해당 버그가 시스템에 미칠 수 있는 영향 수준을 선택해주세요.
      options:
        - (심각도를 선택해주세요)
        - 🛑 CRITICAL - 시스템이 동작하지 않을 수 있음
        - 🟠 HIGH - 주요 기능이 대부분의 상황에서 비정상적으로 동작
        - 🟢 MEDIUM - 특정 상황에서 주요 기능이 문제 발생
        - 🔵 LOW - UI 또는 사소한 이슈 (기능에는 영향 없음)
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 🔍 참고할만한 자료 (선택)
      description: 참고할만한 코드, 재현 방법, 로그, 관련 이슈 등을 자유롭게 추가하세요.
      placeholder: |
        예시:
        - 이슈 #123
        - 콘솔 로그
    validations:
      required: false
