name: '🐛 버그 수정'
description: '기존 설계 목적과 다르게 동작하는 기능 수정'
title: '[FIX] '
labels:
  - 'Type: Fix :bug:'
  - 'Needs-Triage :mag:'
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: 📌 어떤 버그를 수정하나요?
      description: 수정할 버그의 증상과 영향을 간단히 설명해주세요.
      placeholder: |
        예시:
        - 비밀번호 유효성 검사 실패 시에도 회원가입이 되는 문제(#123)
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 📜 수정 상세 내용
      description: 이 버그를 해결하기 위한 작업 내용을 구체적으로 적어주세요.
      placeholder: |
        예시:
        - 유효성 검사를 실패한 경우 가입을 차단하도록 로직 수정
    validations:
      required: true

  - type: textarea
    id: estimate
    attributes:
      label: ⏳ 예상 소요 시간
      description: 예상 소요 시간을 대략적으로 입력해주세요.
      placeholder: |
        예시:
        - 4H
        - 16H ~ 24H
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 🔍 참고할만한 자료
      description: 참고할만한 코드, 재현 방법, 로그, 관련 이슈 등을 자유롭게 추가하세요.
      placeholder: |
        예시:
        - 이슈 #123
        - 콘솔 로그
    validations:
      required: false
