name: '✨ 기능 구현'
description: '새로운 기능 추가 또는 기존 기능 개선 작업'
title: '[FEAT] '
labels:
  - 'Type: Feature :sparkles:'
  - 'Needs-Triage :mag:'
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: 📌 어떤 기능을 구현하나요?
      description: 기능의 목적과 필요성을 3줄 이내로 간결하게 설명해주세요.
      placeholder: |
        예시:
        - 사용자 경험 개선을 위해, 토큰 자동 갱신 기능을 추가한다.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 📜 구현 상세 내용
      description: 기능 구현을 위해 필요한 구체적인 작업 항목을 나열해주세요.
      placeholder: |
        예시:
        - 401 응답 시 리프레시 토큰으로 액세스 토큰을 재발급한다.
    validations:
      required: true

  - type: textarea
    id: estimate
    attributes:
      label: ⏳ 예상 소요 시간
      description: 예상 소요 시간을 대략적으로 입력해주세요.
      placeholder: |
        예시:
        - 4H
        - 16H ~ 24H
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 🔍 참고할만한 자료
      description: 참고할만한 코드, 관련 문서 등을 자유롭게 추가하세요.
      placeholder: |
        예시:
        - [JWT 로그인 구현 가이드](https://...)
    validations:
      required: false
