blank_issues_enabled: true

issue_templates:
  - name: 📝 문서 작성
    description: 기능 설명, 명세서, 개발 가이드 등의 문서 작성
    file: docs.yml

  - name: 🐛 버그 추적
    description: 기존 설계 목적과 다르게 동작하는 기능 추적
    file: bug.yml

  - name: 🎨 UI/UX 개선
    description: 사용자 인터페이스 및 사용자 경험 관련 개선 작업
    file: uiux.yml

  - name: ✨ 기능 구현
    description: 새로운 기능을 추가하거나 기존 기능을 개선합니다
    file: feat.yml

  - name: ♻️ 리팩터링
    description: 코드 구조 개선, 중복 제거, 유지보수성 향상 등의 작업
    file: refactor.yml

  - name: 🐛 버그 수정
    description: 기존 기능에서 발생한 문제를 수정하는 작업
    file: fix.yml
