name: Synchronize develop branch with main

runs:
  using: composite
  steps:
    - name: Set up Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Fetch all branches
      shell: bash
      run: |
        git fetch origin develop
        git checkout develop
        git merge --no-ff origin/main -m "Merge PR #${{ inputs.pr_number }} from main"

    - name: Push to develop
      shell: bash
      run: |
        git push https://x-access-token:${{ inputs.github_token }}@github.com/${{ inputs.repository }} HEAD:develop
