version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/${APP_NAME}:${GITHUB_REF_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    depends_on:
      - ${APP_NAME}-db
    env_file:
      - .env
    networks:
      - ${APP_NAME}-net
    ports:
      - '3000:3000'
    restart: unless-stopped

  postgresql:
    image: postgres:17-alpine
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${APP_NAME}-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ${APP_NAME}-net
    restart: unless-stopped

networks:
  ${APP_NAME}-net:
    driver: bridge

volumes:
  ${APP_NAME}-data:
