version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/${APP_NAME}:dev
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    depends_on:
      - postgresql
    env_file:
      - .env
    networks:
      - app-net
    ports:
      - '3000:3000'
    volumes:
      - app-logs:/app/logs
    restart: unless-stopped

  postgresql:
    image: postgres:17-alpine
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-net
    ports:
      - '5432:5432'
    volumes:
      - app-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

volumes:
  app-data:
  app-logs:
