name: Assign issue author

permissions:
  issues: write

runs:
  using: composite
  steps:
    - name: Assign issue author
      uses: actions/github-script@v7
      with:
        script: |
          const issueNumber = context.payload.issue.number;
          const issueAuthor = context.payload.issue.user.login;

          // 이슈에 작성자 할당
          console.log(`📝 Assigning @${issueAuthor} to issue#${issueNumber}`);
          await github.rest.issues.addAssignees({
            ...context.repo,
            issue_number: issueNumber,
            assignees: [issueAuthor]
          });

          console.log(`✅ Assigned @${issueAuthor} to issue#${issueNumber}`);
