name: Isuse open actions

on:
  issues:
    types: [opened]

jobs: 
  # context 출력
  log-context: 
    runs-on: ubuntu-latest

    steps:
      - name: Console log context
        uses: actions/github-script@v7
        with:
          script: console.log(JSON.stringify(context, null, 2));

  # assignee 등록
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      issues: write # 이슈에 assignee 수정 권한

    steps:
      - name: Assign issue author
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const issueAuthor = context.payload.issue.user.login;

            console.log(`Assigning @${issueAuthor} to issue#${issueNumber}`);

            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: issueNumber,
              assignees: [issueAuthor]
            });
  

  # 브랜치 생성
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 브랜치 생성 권한

    steps:
      # 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 규칙에 따라 브랜치명 설정
      - name: Set branch name
        id: branch-name
        run: |
          BRANCH_NAME="issue/${{ github.event.issue.number }}"
          echo "TARGET_BRANCH=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

      # 브랜치 생성
      - name: Create branch from develop
        run: |
          BASE_BRANCH="develop"
          TARGET_BRANCH=${{ steps.branch-name.outputs.TARGET_BRANCH }}
          echo "Target branch: $TARGET_BRANCH"


          # 원격 브랜치 존재 여부 확인
          if git ls-remote --exit-code --heads origin "$TARGET_BRANCH"; then
            echo "Branch $TARGET_BRANCH already exists. Skipping push."
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            # 브랜치 생성
            git fetch origin $BASE_BRANCH
            git checkout -b "$TARGET_BRANCH" origin/$BASE_BRANCH

            # 빈 커밋 생성
            git commit --allow-empty -m "Create branch for issue #${{ github.event.issue.number }}"
            git push origin "$TARGET_BRANCH"
          fi