name: Issue opened actions

# 트리거: 이슈 생성
on:
  issues:
    types: [opened]

jobs:
  # 체크아웃
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  # assignee 등록
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/assign-author/action.yml

  # 브랜치 생성
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/create-branch/action.yml

  # 풀 리퀘스트 생성
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/create-pull-request/action.yml
