name: Issue opened actions

# 트리거: 이슈 생성
on:
  issues:
    types: [opened]

jobs:
  # assignee 등록
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/assign-author

  # 브랜치 생성
  create-branch:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.create-branch.outputs.branch-name }}
    steps:
      - uses: actions/checkout@v4
      - id: create-branch
        uses: ./.github/actions/create-branch
        with:
          base-branch: main          # 베이스 브랜치
          branch-prefix: issue       # 브랜치 접두사
          ignored-issues: 'bug,docs' # 무시할 이슈 타입

  # 풀 리퀘스트 생성
  create-pull-request:
    needs: create-branch
    if: needs.create-branch.outputs.branch-name != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/create-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: ${{ needs.create-branch.outputs.branch-name }}
          base-branch: main  # 베이스 브랜치
