name: nest.js - CD

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/cd.yml'
      - 'src/**'
      - 'test/**'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'docker/docker-compose.yml'
  workflow_dispatch:

jobs:
  pull-image-and-deploy:
    runs-on: [self-hosted, aws, nest, main] # Actions Runner
    steps:
      # DockerHub 로그인
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 최신 이미지 pull
      - name: Pull image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:main

      # 기존 컨테이너 종료 및 제거
      - name: Stop and remove existing container
        run: |
          sudo docker stop ${{ github.event.repository.name }} || true
          sudo docker rm ${{ github.event.repository.name }} || true

      # 새 컨테이너 실행
      - name: Run container
        run: |
          sudo docker run -d \
            --name ${{ github.event.repository.name }} \
            -p ${{ secrets.DOCKER_PORT_DEV }}:3000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:main

      # 안 쓰는 이미지 정리
      - name: Prune unused images
        run: sudo docker image prune -af
