name: CI (nest.js)

on:
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'test/**'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'docker/docker-compose.yml'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: [self-hosted, aws, nest, main] # Actions Runner
    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 의존성 설치
      - name: Install dependencies
        run: npm ci

      # Lint 실행
      - name: Check lint rules
        run: npm run lint

      # 테스트 실행
      - name: Run test
        run: npm run test

      # DockerHub 로그인
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo -E docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Docker-Compose 빌드
      - name: Docker Compose Build
        run: sudo -E docker compose -f docker/docker-compose.yml build
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          APP_NAME: ${{ github.event.repository.name }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      # Docker 이미지 푸시
      - name: Docker push
        run: sudo -E docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:main
