name: Pull request merged actions

# 트리거: 풀 리퀘스트 병합
on:
  pull_request:
    types: [closed]

jobs:
  # 관련된 이슈 닫기(close, fix, resolve)
  close-related-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: ./.github/actions/close-related-issues

  # 병합이 완료된 브랜치 삭제
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/delete-merged-branch
