name: Pull request merged actions (main)

# 트리거: 풀 리퀘스트 병합(main 브랜치)
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  # develop 브랜치와 main를 동기화
  sync-develop-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: ./.github/actions/sync-develop-main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pr_number: ${{ github.event.pull_request.number }}
